# Generated by Django 5.1 on 2024-08-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='category',
            field=models.CharField(choices=[('Science', 'Science'), ('Arts', 'Arts'), ('Commerse', 'Commerse')], max_length=300),
        ),
    ]
