# Generated by Django 5.1 on 2024-09-23 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_app', '0002_alter_stream_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='subj',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Stream',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
