# Generated by Django 5.1 on 2024-09-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Edu_app', '0003_remove_stream_subj_delete_user_delete_stream_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Streams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, null=True)),
                ('category', models.CharField(max_length=300, null=True)),
                ('subjects', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
