# Generated by Django 5.1 on 2024-09-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_app', '0004_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Streams',
            new_name='Stream',
        ),
    ]
