# Generated by Django 5.1 on 2024-09-23 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_app', '0005_rename_streams_stream'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='stream',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='stream',
            name='subjects',
        ),
        migrations.AddField(
            model_name='stream',
            name='subjects',
            field=models.ManyToManyField(to='Edu_app.subject'),
        ),
    ]
