# Generated by Django 5.1 on 2024-09-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Edu_app', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optimum_learning', models.CharField(choices=[('logical learning', 'logical learning'), ('analitical learning', 'analitical learning'), ('creative learning', 'creative learning')], default='logical learning', max_length=20)),
                ('assesments', models.CharField(choices=[('written exams', 'written exams'), ('tests', 'tests'), ('puzzeles', 'puzzeles')], default='written exams', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
